In [0]:
import numpy as np

# Define arrays 'a' and 'b' for demonstration
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# 1. Array Creation with Zeros
zeros = np.zeros(5)
print("Zeros:", zeros)

# 2. Array Creation with Ones
ones = np.ones(5)
print("Ones:", ones)

# 3. Creating an Identity Matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

# 4. Array Creation with a Specific Value
full_array = np.full((3, 3), 7)
print("Full Array:\n", full_array)

# 5. Array of Evenly Spaced Values (Range)
range_array = np.arange(0, 10, 2)
print("Range Array:", range_array)

# 6. Array of Fixed-Length Steps Between Values (Linspace)
linspace_array = np.linspace(0, 1, 6)
print("Linspace Array:", linspace_array)

# 7. Reshaping an Array
reshaped_array = np.arange(10).reshape(2, 5)
print("Reshaped Array:\n", reshaped_array)

# 8. Flattening a Multi-dimensional Array
flat_array = reshaped_array.flatten()
print("Flat Array:", flat_array)

# 9. Transposing an Array
transposed = reshaped_array.T
print("Transposed Array:\n", transposed)

# 10. Horizontal Stacking of Arrays
h_stack = np.hstack((a, b))
print("Horizontal Stacked:", h_stack)

# 11. Vertical Stacking of Arrays
v_stack = np.vstack((a, b))
print("Vertical Stacked:\n", v_stack)


# 12. Splitting Arrays Horizontally
range_array_2D=range_array.reshape(2,2)
h_split = np.hsplit(range_array_2D, 3)
print("Horizontally Split:", h_split)

# 13. Splitting Arrays Vertically
v_split = np.vsplit(reshaped_array, 2)
print("Vertically Split:\n", v_split)

# 14. Element-wise Addition
element_add = a + b
print("Element-wise Addition:", element_add)

# 15. Element-wise Subtraction
element_sub = a - b
print("Element-wise Subtraction:", element_sub)

# 16. Element-wise Multiplication
element_mul = a * b
print("Element-wise Multiplication:", element_mul)

# 17. Element-wise Division
element_div = a / b
print("Element-wise Division:", element_div)

# 18. Matrix Multiplication (Dot Product)
dot_product = np.dot(a, b)
print("Dot Product:", dot_product)

# 19. Element-wise Square Root
sqrt_array = np.sqrt(a)
print("Square Root:", sqrt_array)

# 20. Sum of Array Elements
sum_array = np.sum(a)
print("Sum of Elements:", sum_array)

# 21. Computing the Mean
mean_array = np.mean(a)
print("Mean:", mean_array)

# 22. Median of Array Elements
median_array = np.median(a)
print("Median:", median_array)

# 23. Finding the Minimum Element
min_array = np.min(a)
print("Minimum Element:", min_array)

# 24. Finding the Maximum Element
max_array = np.max(a)
print("Maximum Element:", max_array)

# 25. Generating Random Numbers
random_array = np.random.random(5)
print("Random Array:", random_array)

###########################################################################################

# Define sample arrays for demonstration
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8], [9, 10], [11, 12]])

# 1. Diagonal Elements of an Array
diagonal = np.diag(a)
print("Diagonal Elements:", diagonal)

# 2. Unique Elements in an Array
unique_elements = np.unique(a)
print("Unique Elements:", unique_elements)

# 3. Element-wise Comparison
elementwise_comparison = np.equal(a, 2)
print("Element-wise Comparison:\n", elementwise_comparison)

# 4. Array Concatenation
concatenated = np.concatenate((a, a), axis=0)
print("Concatenated Array:\n", concatenated)

# 5. Repeat Elements of an Array
repeated = np.repeat(a, 2, axis=0)
print("Repeated Array:\n", repeated)

# 6. Tile an Array
tiled = np.tile(a, (2, 1))
print("Tiled Array:\n", tiled)

# 7. Intersection of Two Arrays
intersection = np.intersect1d(a, b)
print("Intersection:", intersection)

# 8. Set Difference of Two Arrays
set_diff = np.setdiff1d(a, b)
print("Set Difference:", set_diff)

# 9. Array Sorting
sorted_array = np.sort(a, axis=None)
print("Sorted Array:", sorted_array)

# 10. Argsort in Arrays
argsort_array = np.argsort(a, axis=None)
print("Argsort Array:", argsort_array)

# 11. Matrix Multiplication
matrix_mul = np.dot(a, b)
print("Matrix Multiplication:\n", matrix_mul)

# 12. Element-wise Power
power_array = np.power(a, 2)
print("Element-wise Power:\n", power_array)

# 13. Cumulative Sum
cumsum_array = np.cumsum(a)
print("Cumulative Sum:", cumsum_array)

# 14. Cumulative Product
cumprod_array = np.cumprod(a)
print("Cumulative Product:", cumprod_array)

# 15. Standard Deviation
std_dev = np.std(a)
print("Standard Deviation:", std_dev)

# 16. Variance
variance = np.var(a)
print("Variance:", variance)

# 17. Percentile
percentile = np.percentile(a, 50)
print("50th Percentile:", percentile)

# 18. Load Data from File
# data = np.loadtxt('filename.txt')  # Uncomment to use

# 19. Save Array to File
# np.savetxt('output.txt', a)  # Uncomment to use

# 20. Element-wise Sine Function
sine_array = np.sin(a)
print("Sine of Elements:\n", sine_array)

# 21. Element-wise Cosine Function
cosine_array = np.cos(a)
print("Cosine of Elements:\n", cosine_array)

# 22. Element-wise Natural Logarithm
log_array = np.log(a)
print("Natural Logarithm:\n", log_array)

# 23. Create a Meshgrid
x = np.array([0, 1, 2])
y = np.array([0, 1])
xx, yy = np.meshgrid(x, y)
print("Meshgrid XX:\n", xx)
print("Meshgrid YY:\n", yy)

# 24. Find Non-zero Elements
nonzero_elements = np.nonzero(a)
print("Non-zero Elements:", nonzero_elements)

# 25. Clip Array Elements
clipped_array = np.clip(a, 2, 5)
print("Clipped Array:\n", clipped_array)

########################################################################################
######Do not look at it now ############################################################
# 1. Eigenvalues and Eigenvectors
# Problem: Compute the eigenvalues and eigenvectors of a matrix.
matrix = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# 2. Singular Value Decomposition (SVD)
# Problem: Perform SVD on a matrix.
u, s, vt = np.linalg.svd(matrix)
print("U Matrix:\n", u)
print("Sigma Values:", s)
print("V Transpose Matrix:\n", vt)

# 3. Solving Linear Systems
# Problem: Solve the linear equation Ax = B for x.
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])
x = np.linalg.solve(A, B)
print("Solution of Linear System:", x)

# 4. Fourier Transform for Signal Processing
# Problem: Apply Fourier transform to a signal.
t = np.linspace(0, 1, 500)
signal = np.sin(2 * np.pi * 60 * t) + np.sin(2 * np.pi * 120 * t)
f_signal = np.fft.fft(signal)
print("Fourier Transform:\n", f_signal)

# 5. Polynomial Fitting
# Problem: Fit a polynomial to data points.
x = np.array([0, 1, 2, 3, 4, 5])
y = np.array([0, 0.8, 0.9, 0.1, -0.8, -1])
z = np.polyfit(x, y, 3)
p = np.poly1d(z)
print("Polynomial coefficients:", z)
print("Polynomial:\n", p)

# 6. Cross-correlation of Two Signals
# Problem: Compute the cross-correlation of two signals.
a = np.array([1, 2, 3])
b = np.array([0, 1, 0.5])
corr = np.correlate(a, b, "full")
print("Cross-correlation:", corr)

# 7. Random Sampling from a Distribution
# Problem: Generate samples from a normal distribution.
samples = np.random.normal(0, 1, 1000)
print("Random Samples:", samples[:10])

# 8. Covariance Matrix
# Problem: Compute the covariance matrix for a dataset.
data = np.array([[1, 2, 1], [3, 4, 3], [5, 6, 5]])
cov_matrix = np.cov(data)
print("Covariance Matrix:\n", cov_matrix)

# 9. Principal Component Analysis (PCA)
# Problem: Perform PCA on a dataset.
mean = np.mean(data, axis=0)
data_adjusted = data - mean
u, s, v = np.linalg.svd(data_adjusted)
pca = np.dot(data_adjusted, v.T)
print("PCA:\n", pca)

# 10. Filtering Signal with a Convolution
# Problem: Apply a convolution filter to a signal.
kernel = np.array([1, 2, 1])
convoluted = np.convolve(signal, kernel, 'same')
print("Convoluted Signal:", convoluted)

# 11. Generating a Markov Transition Matrix
# Problem: Create a Markov matrix for a given state transition data.
transitions = np.array([[0.8, 0.1, 0.1], [0.2, 0.7, 0.1], [0.1, 0.3, 0.6]])
print("Markov Transition Matrix:\n", transitions)

# 12. Gradient of a Function
# Problem: Compute the gradient of a 2D function.
x, y = np.meshgrid(np.linspace(-2, 2, 5), np.linspace(-2, 2, 5))
z = x ** 2 + y ** 2
gradient = np.gradient(z)
print("Gradient of Function:\n", gradient)

# 13. Solving Eigenvalue Problem for a Sparse Matrix
# Problem: Solve for eigenvalues and eigenvectors of a large sparse matrix.
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import eigs
sparse_matrix = csr_matrix(matrix)
vals, vecs = eigs(sparse_matrix, k=2)
print("Eigenvalues of Sparse Matrix:", vals)
print("Eigenvectors of Sparse Matrix:\n", vecs)

# 14. Inverse of a Matrix
# Problem: Compute the inverse of a matrix.
inverse_matrix = np.linalg.inv(A)
print("Inverse of Matrix:\n", inverse_matrix)

# 15. Determinant of a Matrix
# Problem: Compute the determinant of a matrix.
determinant = np.linalg.det(A)
print("Determinant of Matrix:", determinant)

# 16. Rank of a Matrix
# Problem: Find the rank of a matrix.
rank = np.linalg.matrix_rank(A)
print("Rank of Matrix:", rank)

# 17. Orthogonalization of a Matrix (QR Decomposition)
# Problem: Perform QR decomposition on a matrix.
Q, R = np.linalg.qr(matrix)
print("Orthogonal Matrix Q:\n", Q)
print("Upper Triangular Matrix R:\n", R)

# 18. Fast Fourier Transform (FFT) for Signal Processing
# Problem: Compute the FFT of a signal.
fft_signal = np.fft.fft(signal)
print("FFT of Signal:\n", fft_signal)

# 19. Inverse Fast Fourier Transform (IFFT)
# Problem: Compute the inverse FFT of a signal.
ifft_signal = np.fft.ifft(fft_signal)
print("IFFT of Signal:\n", ifft_signal)

# 20. Discrete Cosine Transform (DCT)
# Problem: Compute the DCT of a signal.
from scipy.fftpack import dct
dct_signal = dct(signal)
print("DCT of Signal:\n", dct_signal)

# 21. Discrete Wavelet Transform (DWT)
# Problem: Perform DWT on a signal.
from pywavelets import dwt
coeffs = dwt(signal, 'haar')
print("DWT Coefficients:", coeffs)

# 22. Optimization with Gradient Descent
# Problem: Find the minimum of a simple function using gradient descent.
def f(x):
    return x ** 2

def df(x):
    return 2 * x

x = 10  # Initial guess
for _ in range(100):
    x -= 0.1 * df(x)
print("Minimum found at:", x)

# 23. Interpolation of Missing Data
# Problem: Interpolate missing values in a dataset.
from scipy.interpolate import interp1d
x = np.linspace(0, 10, num=10, endpoint=True)
y = np.cos(-x**2 / 9.0)
y[5] = np.nan  # Introduce a missing value
f = interp1d(x, y, kind='linear', fill_value='extrapolate')
y_interpolated = f(x)
print("Interpolated Data:", y_interpolated)

# 24. Image Processing: Edge Detection
# Problem: Apply edge detection to an image array.
from scipy.ndimage import convolve, sobel
image = np.random.random((10, 10))
edges = sobel(image)
print("Edge Detected Image:\n", edges)

# 25. Time Series Analysis: Autocorrelation
# Problem: Compute the autocorrelation of a time series.
time_series = np.random.random(100)
autocorrelation = np.correlate(time_series, time_series, mode='full')
print("Autocorrelation of Time Series:", autocorrelation)

# Note: Some operations require additional libraries like scipy or pywavelets.






Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Full Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Range Array: [0 2 4 6 8]
Linspace Array: [0.  0.2 0.4 0.6 0.8 1. ]
Reshaped Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Flat Array: [0 1 2 3 4 5 6 7 8 9]
Transposed Array:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
Horizontal Stacked: [1 2 3 4 5 5 4 3 2 1]
Vertical Stacked:
 [[1 2 3 4 5]
 [5 4 3 2 1]]


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File <command-1021949250191137>, line 53
     49 print("Vertical Stacked:\n", v_stack)
     52 # 12. Splitting Arrays Horizontally
---> 53 range_array_2D=range_array.reshape(2,2)
     54 h_split = np.hsplit(range_array_2D, 3)
     55 print("Horizontally Split:", h_split)

ValueError: cannot reshape array of size 5 into shape (2,2)