In [0]:
###Array
###lists
###numPy
####lists
###


####
###data is not stored in Contnous location
###indexing difficult for lists
###
####arrays are stored in a contnous location
###homogenious data sets
###import numpy
import numpy as np
arr=np.array([1,2,3])
print(arr)








[1 2 3]


In [0]:
probability1=[0.6,0.3,0.4]
probability2=[0.2,0.4,0.7]
#combinedPrbability=probability1*probability2
arrProb1=np.array(probability1)
arrProb2=np.array(probability2)
combinedPrbability=arrProb1*arrProb2
print(combinedPrbability)

[0.12 0.12 0.28]


In [0]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D)
print(arr2D[1,1])
arr2D[1,1]=12
print(arr2D)

newarr=arr2D.ravel()
print(newarr)
print(newarr[0])

####
zeroArr=np.ones((2,3))
print(zeroArr)

###identity matrix
###
arrEye=np.eye(3)
print(arrEye)

####reshaping







[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]
[ 1  2  3  4 12  6  7  8  9]
1
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D)

reshapedArray=arr2D.reshape(3,4)
print(reshapedArray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [0]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D)
sumarray=np.sum(arr2D)
print(sumarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
78


In [0]:


# Assuming 365 days for simplicity, representing one year
num_days = 366


dates = np.arange(np.datetime64('2020-01-01'), np.datetime64('2021-01-01'))
temperatures = np.random.normal(20, 5, num_days)  # Avg temp of 20°C with some variation
precipitations = np.random.uniform(0, 20, num_days)  # Random precipitation between 0 and 20mm

# Combine into a single structured array
dtype = [('date', 'datetime64[D]'), ('temperature', float), ('precipitation', float)]
weather_data = np.zeros(num_days, dtype=dtype)
print(weather_data)

weather_data['date'] = dates
weather_data['temperature'] = temperatures
weather_data['precipitation'] = precipitations
#print(weather_data)
#print(precipitations)


[('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.) ('1970-01-01', 0., 0.)
 ('1970-01-01', 0., 

In [0]:
#Calculate monthly average temperatures:
##get unique months
        ###create an numpy array for months
        ###run the unique operations
months = np.array([date.astype('datetime64[M]') for date in weather_data['date']])
unique_months = np.unique(months)
print(unique_months)
###create the average for those months
###mean date.astype("")
for month in unique_months:
    avg_temp = np.mean(weather_data['temperature'])
    
    print(month, avg_temp)





['2020-01' '2020-02' '2020-03' '2020-04' '2020-05' '2020-06' '2020-07'
 '2020-08' '2020-09' '2020-10' '2020-11' '2020-12']
2020-01 19.99160290023396
2020-02 19.99160290023396
2020-03 19.99160290023396
2020-04 19.99160290023396
2020-05 19.99160290023396
2020-06 19.99160290023396
2020-07 19.99160290023396
2020-08 19.99160290023396
2020-09 19.99160290023396
2020-10 19.99160290023396
2020-11 19.99160290023396
2020-12 19.99160290023396


In [0]:
##createing grades for the learners 
##mean median and stndard deviation from the numpy functions
###the learners who need most of the help
###where clause in np
grades = np.random.randint(50, 100, size=10)
mean=np.mean(grades)
median=np.median(grades)
std=np.std(grades)
print(grades)
print(mean, median, std)

####learners need most help
thresholdvalue=mean-std
helpStudents=np.where(grades<thresholdvalue)[0]
print(helpStudents)

####overachievers : identify the 10% of the class
##overachievers:  identify the top 10
percentile=np.percentile(grades,10)
print(percentile)
top_10_percent_threshold = np.percentile(grades, 90)
overachiever=np.where(grades>=top_10_percent_threshold)[0]
print(overachiever)
###numpy implementation
###numpy functions
###2D array implementations




[51 76 83 80 85 81 98 81 80 92]
80.7 81.0 11.645170672858342
[0]
73.5
[6]
